### ISSUE TITLE
binary_sensor.speedtest_running does not update

### ISSUE THREAD

**Issue by jpettitt** [MrSuicideParrot/hassio-speedtest-addon#12]
When I launch speed test from an automation the sate of `binary_sensor.speedtest_running` does not change.  I'd like to be able to have an entity displayed for `binary_sensor.speedtest_running` with a tap action to start the test and have the entity state reflect that it's actually running but it doesn't seem to work.

My current workaround is to set a helper to "running" and and then wait for the upoload value to update and clear the helper.

```yaml
alias: Internet Speed Test
description: ""
trigger: []
condition: []
action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.speed_test_running
  - service: hassio.addon_start
    data:
      addon: 6b87c29e_speedtest_addon
  - wait_for_trigger:
      - platform: state
        entity_id:
          - sensor.speedtest_upload
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.speed_test_running
mode: single
```
